### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [robbdimitrov/pixelgram#5]
Hi @robbdimitrov , i am a logo designer. 

I contribute to open source projects that do not have logo. I designed a logo representing the function and name of the project. The logo concept description is available in the following image. What do you think? I wail wait for feedback. Have a nice day!

![pixelgram](https://user-images.githubusercontent.com/36298335/56437374-ca268400-62e7-11e9-9fbc-093775879695.jpg)

Readme view;

![pix](https://user-images.githubusercontent.com/36298335/56437410-f4784180-62e7-11e9-8010-bca194be2b0f.png)

**Comment by robbdimitrov** [comment]
Hi @reallinfo :)
This looks awesome!

**Comment by reallinfo** [comment]
Thanks :) If you don't want to make any changes, i can send a pr.

**Comment by robbdimitrov** [comment]
Whatever is easier for you :)

**Comment by reallinfo** [comment]
Well, I think angular color is very suitable for the representation and function of the software. I sent a pr. 

If you need help with the logo, you can contact me.

**Comment by robbdimitrov** [comment]
It's awesome! :) Thank you! 🍻 🚀
